# version: '3.8'

services:
  gacha-backend:
    build: .
    container_name: genshin_sim_server
    ports:
      - "8000:8000"
    volumes:
      # Maps the local Data folder to the container's Data folder.
      - ./Data:/app/Data
    restart: unless-stopped